table! {
    /// Representation of the `answers` table.
    ///
    /// (Automatically generated by Diesel.)
    answers (id) {
        /// The `id` column of the `answers` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `author` column of the `answers` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        author -> Integer,
        /// The `question` column of the `answers` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        question -> Integer,
        /// The `time` column of the `answers` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        time -> Timestamp,
        /// The `score` column of the `answers` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        score -> Integer,
        /// The `accepted` column of the `answers` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        accepted -> Bool,
        /// The `text` column of the `answers` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        text -> Text,
    }
}

table! {
    /// Representation of the `chosen_tags` table.
    ///
    /// (Automatically generated by Diesel.)
    chosen_tags (id) {
        /// The `id` column of the `chosen_tags` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `question` column of the `chosen_tags` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        question -> Integer,
        /// The `tag` column of the `chosen_tags` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        tag -> Integer,
    }
}

table! {
    /// Representation of the `questions` table.
    ///
    /// (Automatically generated by Diesel.)
    questions (id) {
        /// The `id` column of the `questions` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `author` column of the `questions` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        author -> Integer,
        /// The `time` column of the `questions` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        time -> Timestamp,
        /// The `score` column of the `questions` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        score -> Integer,
        /// The `title` column of the `questions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Text,
        /// The `text` column of the `questions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        text -> Text,
    }
}

table! {
    /// Representation of the `tags` table.
    ///
    /// (Automatically generated by Diesel.)
    tags (id) {
        /// The `id` column of the `tags` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `tags` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
    }
}

table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `username` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        username -> Text,
        /// The `passowrd` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        passowrd -> Text,
    }
}

joinable!(answers -> questions (question));
joinable!(answers -> users (author));
joinable!(chosen_tags -> questions (question));
joinable!(chosen_tags -> tags (tag));
joinable!(questions -> users (author));

allow_tables_to_appear_in_same_query!(
    answers,
    chosen_tags,
    questions,
    tags,
    users,
);
